spring.application.name=smart-clinic-api
spring.datasource.url=jdbc:mysql://localhost:3306/smart_clinic_db
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

spring.data.mongodb.uri=mongodb://localhost:27017/smart_clinic
